apiVersion: v1
kind: Secret
metadata:
  name: token
data:
  token: insert_token_here_in_base64
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: settings
  name: settings
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: discord-usos-auth
  name: discord-usos-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-usos-auth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: discord-usos-auth
    spec:
      containers:
        - env:
            - name: SETTINGS_FILE
              value: /etc/discord-usos-auth/config/settings.json
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: token
                  key: token
          image: navareth/discord-usos-auth:latest
          name: discord-usos-auth
          volumeMounts:
            - mountPath: /etc/discord-usos-auth/config
              name: settings
      restartPolicy: Always
      volumes:
        - name: settings
          persistentVolumeClaim:
            claimName: settings
